---
title: "FattyAcidAnalysis"
author: "JustJaxz | J Stuart"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
### Load Libs
```{r load_libs}
library("dplyr")
library("ggpubr")
library("patchwork")
library("stringr")  
library("gridExtra")
library("tidyr")

```

### Load and subset data

```{r load_data}
setwd("C:/Users/user1/Documents/R") # Set working dir
fame <- read.csv("C:/Users/user1/Documents/R/data/FAME_data_perc.csv") # load data

# Subsetting data
pola <- subset(fame, isolate == "polarella")
nitz <- subset(fame, isolate == "nitzschia")

# Defining FA data
acids <- c("lauric.acid", "myristic.acid", "palmitic.acid", "palmitoleic.acid", 
           "hexadecadienoic.acid", "stearic.acid", "oleic.acid", "linoleic.acid", 
           "SDA", "eicosatrienoic.acid", "AA", 
           "eicosapentaenoic.acid", "DHA", "SFA", "MUFA", "PUFA", "n.3.PUFA", "perc.FA.reported", "fat.perc")
```

### Check Normalicy of data {.tabset}
#### Polarella
```{r norm_Pola_qqplot}
set.seed(1234)

pola_plots <- list()

# Loop through each acid to create ggplot objects
for (acid in acids) {
  plot_title <- paste0(str_replace(acid, "\\.", " "), " Distribution")
  p <- ggqqplot(pola[[acid]]) + 
    labs(title = plot_title, y = "% fat Content") +
    theme(axis.text = element_text(size = 6),
          axis.title = element_text(size = 8),
          plot.title = element_text(size = 8))
  
  pola_plots[[acid]] <- p
}

# Arrange plots in a grid with 4 columns
pola_grid_arrange <- wrap_plots(pola_plots, ncol = 6)
pola_grid_arrange <- pola_grid_arrange + ggtitle("Polarella FAME Distributions")
```
  
  
#### Nitzschia
```{r norm_Nitz_qqplot}
set.seed(1234)

nitz_plots <- list()

# Loop through each acid to create ggplot objects
for (acid in acids) {
  plot_title <- paste0(str_replace(acid, "\\.", " "), " Distribution")
  p <- ggqqplot(nitz[[acid]]) + 
    labs(title = plot_title, y = "% fat Content") +
    theme(axis.text = element_text(size = 6),
          axis.title = element_text(size = 8),
          plot.title = element_text(size = 8))
  
  nitz_plots[[acid]] <- p
}

# Arrange plots in a grid with 4 columns
nitz_grid_arrange <- wrap_plots(nitz_plots, ncol = 6)
nitz_grid_arrange <- nitz_grid_arrange + ggtitle("Nitzschia FAME Distributions")

```
###{-}